-- Creamos la tabla ingredientes 
CREATE TABLE Ingredientes (
    codIngrediente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alergenos CHAR(1) DEFAULT 'N', -- 'S' para 'sí contiene', 'N' para 'no contiene'
    nombre VARCHAR2(50) NOT NULL,
    sabor VARCHAR2(50) -- Lista de los diferentes valores que puede tomar sabor
        CHECK (sabor IN ('Salado', 'Dulce', 'Amargo', 'Agrio', 'Ácido', 
                         'Agridulce', 'Neutro', 'Aromático', 'Picante', 
                         'Graso', 'Crujiente'))
);


-- Creamos la tabla comidas
CREATE TABLE Comidas (
    codComida NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50)  NOT NULL,
    tipo VARCHAR2(50),
    descripcion CLOB,
    origen VARCHAR2(50),
    alergenos CHAR(1) DEFAULT 'N' -- 'S' para 'sí', 'N' para 'no'
);


-- Creamos la tabla alergenos
CREATE TABLE Alergenos (
    codAlergeno NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(60)  NOT NULL
);


-- Creamos la tabla comida_ingredientes
CREATE TABLE comida_ingredientes (
    codComidaIngredientes NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codComida NUMBER REFERENCES Comidas(codComida) ON DELETE SET NULL,
    codIngrediente NUMBER REFERENCES Ingredientes(codIngrediente) ON DELETE SET NULL,
    cantidad VARCHAR2(50)
);


-- Creamos la tabla ingrediente_alergenos
CREATE TABLE ingrediente_alergenos (
    codIngredientesAlergenos NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codIngrediente NUMBER REFERENCES Ingredientes(codIngrediente) ON DELETE SET NULL,
    codAlergeno NUMBER REFERENCES Alergenos(codAlergeno) ON DELETE SET NULL
);


